"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Download, PackageCheck, ShoppingBag, TrendingUp, Users } from "lucide-react";
import { formatCurrency } from "@/data/shop";
import { getOrders, getProducts, getUsers } from "@/utils/shopStorage";

export default function AdminDashboard() {
  const [orders, setOrders] = useState([]);
  const [products, setProducts] = useState([]);
  const [users, setUsers] = useState([]);
  useEffect(() => { setOrders(getOrders()); setProducts(getProducts()); setUsers(getUsers()); }, []);
  const revenue = orders.reduce((sum, order) => sum + Number(order.total || 0), 0);
  const pending = orders.filter((order) => !["Hoàn thành", "Đã hủy"].includes(order.status)).length;
  const stats = [{ label: "Doanh thu", value: formatCurrency(revenue), icon: TrendingUp, tone: "text-emerald-300 bg-emerald-400/10" }, { label: "Đơn cần xử lý", value: pending, icon: PackageCheck, tone: "text-orange-300 bg-orange-400/10" }, { label: "Sản phẩm", value: products.length, icon: ShoppingBag, tone: "text-blue-300 bg-blue-400/10" }, { label: "Thành viên", value: users.length, icon: Users, tone: "text-violet-300 bg-violet-400/10" }];
  const chart = useMemo(() => [32, 44, 38, 58, 65, 52, 78, 72, 86, 91, 84, 96], []);
  return <div className="space-y-6"><section className="admin-card overflow-hidden rounded-3xl"><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="p-7"><p className="text-xs font-black uppercase tracking-[0.25em] text-orange-300">Dashboard</p><h2 className="mt-3 text-3xl font-black">Tổng quan vận hành</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Theo dõi doanh thu, trạng thái đơn hàng, tồn kho và hiệu quả khuyến mãi trong một màn hình.</p><button className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-orange-500 px-5 py-3 text-sm font-black text-white"><Download size={16} /> Xuất báo cáo</button></div><img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&auto=format&fit=crop&q=80" alt="Dashboard" className="h-64 w-full object-cover opacity-70 lg:h-full" /></div></section><section className="grid gap-4 md:grid-cols-4">{stats.map((stat) => { const Icon = stat.icon; return <div key={stat.label} className="admin-card rounded-3xl p-5"><div className={"mb-4 flex h-11 w-11 items-center justify-center rounded-2xl " + stat.tone}><Icon size={21} /></div><p className="text-sm font-bold text-slate-400">{stat.label}</p><p className="mt-2 text-2xl font-black">{stat.value}</p><p className="mt-2 flex items-center gap-1 text-xs font-bold text-emerald-300"><ArrowUpRight size={14} /> Tăng trưởng ổn định</p></div>; })}</section><section className="grid gap-6 lg:grid-cols-[1fr_420px]"><div className="admin-card rounded-3xl p-6"><div className="mb-6 flex items-center justify-between"><div><h3 className="font-black">Doanh thu theo tháng</h3><p className="text-xs text-slate-500">Đơn vị quy đổi theo triệu VND</p></div></div><div className="flex h-64 items-end gap-3">{chart.map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-xl bg-gradient-to-t from-orange-600 to-orange-300" style={{ height: height + "%" }} /><span className="text-[11px] font-bold text-slate-500">T{index + 1}</span></div>)}</div></div><div className="admin-card rounded-3xl p-6"><h3 className="font-black">Đơn mới tiếp nhận</h3><div className="mt-4 space-y-3">{orders.slice(0, 5).map((order) => <div key={order.id} className="rounded-2xl bg-white/5 p-4"><div className="flex items-center justify-between"><p className="font-black text-orange-300">#{order.id}</p><span className="text-xs font-bold text-slate-400">{order.status}</span></div><p className="mt-1 text-sm font-bold text-white">{order.customerName}</p><p className="mt-2 text-sm text-slate-400">{formatCurrency(order.total)} - {order.paymentMethod}</p></div>)}</div></div></section></div>;
}
